import turtle

janela= turtle.Screen()
tat = turtle.Turtle()
tat.shape("turtle")
tat.color("red")
tat.left(90)
tat.forward(100)
tat.right(38)
tat.forward(200)
tat.left(57)
tat.forward(50)
tat.right(9)
tat.right(10)
tat.forward(100)
